FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY ["MemberRegister.WebApi/MemberRegister.WebApi.csproj", "MemberRegister.WebApi/"]
RUN dotnet restore "MemberRegister.WebApi/MemberRegister.WebApi.csproj"
COPY . .
WORKDIR "/src/MemberRegister.WebApi"
RUN dotnet build "MemberRegister.WebApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MemberRegister.WebApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MemberRegister.WebApi.dll"]
